### ISSUE TITLE
Core compatibility

### ISSUE THREAD

**Issue by davidglassborow** [kthompson/Actress#1]
Hi, love this library, use it all the time (when I can't use F#).

Could you update the nuget package to make it support .net standard so we can use it in core please ?

Looking at the code there should be no problems, should be 100% compatible.

**Comment by kthompson** [comment]
Sure. I can take a look this weekend. If you want to submit a PR I would be happy to check it out and push it to nuget.

**Comment by kthompson** [comment]
Took a while to get to this but I just uploaded 0.2.0 to nuget which supports dotnet core. If you have any troubles please let me know.

**Comment by davidglassborow** [comment]
Brilliant, thanks !
